version: '3'
services:
    postgres:
        image: postgres:11.2-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: bridges
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: bridges
        ports:
            - "54321:5432"
    nginx:
        build: docker/nginx
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        volumes:
            - ./frontend/build:/bridges/frontend
        depends_on:
            - php-fpm
        environment:
            TZ: ${TZ}
        ports:
            - 80:80

    php-fpm:
        build: docker/php-fpm
        container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
        volumes:
            - ./backend:/bridges
        depends_on:
            - postgres
        environment:
            TZ: ${TZ}
            PHP_IDE_CONFIG: "serverName=bridges"
#            XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"

    php-cli:
        build: docker/php-cli
        container_name: ${COMPOSE_PROJECT_NAME}-php-cli
        volumes:
            - ./backend:/bridges
            - composer:/root/.composer/cache
        depends_on:
            - postgres
        environment:
            TZ: ${TZ}

#    redis:
#        image: redis:3.0-alpine
#        container_name: ${COMPOSE_PROJECT_NAME}_redis
#        volumes:
#            - redis:/data
#        command: redis-server
#            #--requirepass secret

    mailer:
        image: mailhog/mailhog
        container_name: ${COMPOSE_PROJECT_NAME}-mailer
        ports:
        - "8025:8025"

volumes:
    postgres:
    composer:
    redis:
