parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            uuid: 'Ramsey\Uuid\Doctrine\UuidType'
            user_email: 'App\Model\User\Entity\User\EmailType'
            user_role: 'App\Model\User\Entity\User\RoleType'
            employee_email: 'App\Model\Stuff\Entity\Employee\EmailType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Process:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Process/Entity'
                prefix: 'App\Model\Process\Entity'
            Stuff:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Stuff/Entity'
                prefix: 'App\Model\Stuff\Entity'
                alias: Process
