const AUTH_REQUEST = 'AUTH_REQUEST'
const AUTH_SUCCESS = 'AUTH_SUCCESS'
const AUTH_FAILURE = 'AUTH_FAILURE'
const LOGOUT = 'LOGOUT'
const RESTORE_AUTH = 'RESTORE_AUTH'

export { AUTH_REQUEST, AUTH_SUCCESS, AUTH_FAILURE, LOGOUT, RESTORE_AUTH }
