const PROCESS_REQUEST = 'PROCESS_REQUEST',
    PROCESS_SUCCESS = 'PROCESS_SUCCESS',
    PROCESS_FAILURE = 'PROCESS_FAILURE',
    PROCESS_SAVE = 'PROCESS_SAVE'

export { PROCESS_REQUEST, PROCESS_SUCCESS, PROCESS_FAILURE, PROCESS_SAVE }