const PROCESS_LIST_REQUEST = 'PROCESS_LIST_REQUEST'
const PROCESS_LIST_SUCCESS = 'PROCESS_LIST_SUCCESS'
const PROCESS_LIST_FAILURE = 'PROCESS_LIST_FAILURE'

export { PROCESS_LIST_REQUEST, PROCESS_LIST_SUCCESS, PROCESS_LIST_FAILURE }
