const PROCESS_REQUEST = 'PROCESS_REQUEST'
const PROCESS_SUCCESS = 'PROCESS_SUCCESS'
const PROCESS_FAILURE = 'PROCESS_FAILURE'
const PROCESS_SAVE = 'PROCESS_SAVE'

export { PROCESS_REQUEST, PROCESS_SUCCESS, PROCESS_FAILURE, PROCESS_SAVE }
