const PROCESS_LIST_REQUEST = 'PROCESS_LIST_REQUEST',
    PROCESS_LIST_LOADED = 'PROCESS_LIST_LOADED',
    PROCESS_LIST_FAILURE = 'PROCESS_LIST_FAILURE'

export { PROCESS_LIST_REQUEST, PROCESS_LIST_LOADED, PROCESS_LIST_FAILURE }