const TICKET_LIST_REQUEST = 'TICKET_LIST_REQUEST',
    TICKET_LIST_LOADED = 'TICKET_LIST_LOADED',
    TICKET_LIST_FAILURE = 'TICKET_LIST_FAILURE'

export { TICKET_LIST_REQUEST, TICKET_LIST_LOADED, TICKET_LIST_FAILURE }