const TICKET_LIST_REQUEST = 'TICKET_LIST_REQUEST'
const TICKET_LIST_SUCCESS = 'TICKET_LIST_SUCCESS'
const TICKET_LIST_FAILURE = 'TICKET_LIST_FAILURE'

export { TICKET_LIST_REQUEST, TICKET_LIST_SUCCESS, TICKET_LIST_FAILURE }
